name: CI

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4.1.3

      - run: |
          git config --local core.autocrlf true
          git config --local user.name "Microsoft GitHub User"
          git config --local user.email msftgits@microsoft.com

      - run: |
          cd .\tools
          .\launch.ps1 > ..\defconfig

      - run: |
          git add defconfig
          git commit --message "Update to the latest Microsoft 365 builds"
          git push
