name: Office16 (prod)

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 17.3.0

      - run: |
          sh tools/launch.sh

      - run: |
          git config --local core.autocrlf true
          git config --local user.name "Microsoft GitHub User"
          git config --local user.email msftgits@microsoft.com

      - run: |
          git add .
          git commit --message "$(date)"
          git push
