name: Office16 (prod)

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.4.0

      - run: |
          sh tools/launch.sh

      - run: |
          git config core.autocrlf true
          git config user.name "Microsoft GitHub User"
          git config user.email msftgits@microsoft.com

      - run: |
          git add .
          git commit -m "$(date)"
          git push
